function [xNew] = updateVal(u,x,q0)
%UPDATEX Summary of this function goes here
%   Detailed explanation goes here

if (size(u,1)<3)
    r = 1;
end

parameters;

wr = x(9);

if isempty(r)
   r = u(3,:);
end


VSL =   [
    VSL0;...
    u(1);...
    u(2);...
    VSL0];

V  = [  
    min([ (1+alph)* VSL(1), vf*exp(-1/a*(x(1)/rhoc)^a)]);...
    min([ (1+alph)* VSL(2), vf*exp(-1/a*(x(2)/rhoc)^a)]);...
    min([ (1+alph)* VSL(3), vf*exp(-1/a*(x(3)/rhoc)^a)]);...
    min([ (1+alph)* VSL(4), vf*exp(-1/a*(x(4)/rhoc)^a)])];

q = [   
    lambda*x(1)*x(5);...
    lambda*x(2)*x(6);...
    lambda*x(3)*x(7);...
    lambda*x(4)*x(8)];

qr = min([r*Cr, Dr + wr/T, Cr* (rhom-x(4)/lambda)/(rhom-rhoc)]);

xNew = [ 
    x(1) + T/(lambda*L)*(q0 - q(1))/3600;...
    x(2) + T/(lambda*L)*(q(1) - q(2))/3600;...
    x(3) + T/(lambda*L)*(q(2) - q(3))/3600;
    x(4) + T/(lambda*L)*(q(3) - q(4) + qr)/3600;...
    ...
    x(5) + T/tau * (V(1) - x(5))                             - muu*T/(tau*L) * (x(2)-x(1))/(x(1)+K);...
    x(6) + T/tau * (V(2) - x(6)) + T/L*x(6)*(x(5)-x(6))/3600 - muu*T/(tau*L) * (x(3)-x(2))/(x(2)+K);...
    x(7) + T/tau * (V(3) - x(7)) + T/L*x(7)*(x(6)-x(7))/3600 - muu*T/(tau*L) * (x(4)-x(3))/(x(3)+K);...
    x(8) + T/tau * (V(4) - x(8)) + T/L*x(8)*(x(7)-x(8))/3600 ;...
    x(9) + T*(Dr - qr)/3600 ];

end

